# Generated by Django 3.2.2 on 2021-05-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perros',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('raza', models.CharField(max_length=20)),
                ('edad', models.CharField(max_length=2)),
                ('peso', models.CharField(max_length=3)),
                ('color', models.CharField(max_length=20)),
                ('entrenado', models.BooleanField(default=True)),
            ],
        ),
    ]
